
<footer>
	<div class="container">
		<div class="row">


			<div class="widgets">

				<div class="col-md-3">
					<div class="fwidget">

						<h4>Contact</h4>

						<p>Nullam justo nunc, dignissim at convallis posuere, sodales eu orci. </p>
						<hr />
						<i class="fa fa-home"></i> &nbsp; 123, Some Area. Los Angeles, CA, 54321.
						<hr />
						<i class="fa fa-phone"></i> &nbsp; +239-3823-3434
						<hr />
						<i class="fa fa-envelope-o"></i> &nbsp; <a href="mailto:#">someone@company.com</a>
						<hr />
						<div class="social">
							<a href="#" class="bblue"><i class="fa fa-facebook"></i></a>
							<a href="#" class="borange"><i class="fa fa-google-plus"></i></a>
							<a href="#" class="blightblue"><i class="fa fa-twitter"></i></a>
							<a href="#" class="bviolet"><i class="fa fa-linkedin"></i></a>
							<a href="#" class="bred"><i class="fa fa-pinterest"></i></a>
							<a href="#" class="borange"><i class="fa fa-rss"></i></a>
						</div>

					</div>
				</div>

				<div class="col-md-3">
					<div class="fwidget">
						<h4>Categories</h4>
						<ul>
							<li><a href="#">Condimentum - Condimentum gravida</a></li>
							<li><a href="#">Etiam at - Condimentum gravida</a></li>
							<li><a href="#">Fusce vel - Condimentum gravida</a></li>
							<li><a href="#">Vivamus - Condimentum gravida</a></li>
							<li><a href="#">Pellentesque - Condimentum gravida</a></li>
							<li><a href="#">Fusce vel - Condimentum gravida</a></li>
						</ul>
					</div>
				</div>

				<div class="col-md-3">
					<div class="fwidget">

						<h4>Subscribe</h4>
						<p>Duis leo risus, condimentum ut posuere ac, vehicula luctus nunc.  Quisque rhoncus, a sodales enim arcu quis turpis.</p>
						<p>Enter you email to Subscribe</p>

						<form class="form-inline" role="form">
							<div class="input-group">
								<input type="text" class="form-control" id="subscribe" placeholder="Subscribe...">
								<span class="input-group-btn">
					<button type="submit" class="btn btn-danger">Subscribe</button>
				</span>
							</div>
						</form>

					</div>
				</div>

				<div class="col-md-3">
					<div class="fwidget">
						<h4>Recent Posts</h4>
						<ul>
							<li><a href="#">Sed eu leo orci, condimentum gravida metus</a></li>
							<li><a href="#">Etiam at nulla ipsum, in rhoncus purus</a></li>
							<li><a href="#">Fusce vel magna faucibus felis dapibus facilisis</a></li>
							<li><a href="#">Vivamus scelerisque dui in massa</a></li>
							<li><a href="#">Pellentesque eget adipiscing dui semper</a></li>
						</ul>
					</div>
				</div>

			</div>
		</div>
		<div class="row">
			<div class="col-md-12">
				<div class="copy">
					<p>Copyright &copy; <a href="#">Your Site</a> - <a href="index.html">Home</a> | <a href="aboutus.html">About Us</a> | <a href="faq.html">FAQ</a> | <a href="contactus.html">Contact Us</a></p>
				</div>
			</div>

		</div>
		<div class="clearfix"></div>
	</div>
</footer>

<!-- This page JS -->

</body>
</html>
