<!DOCTYPE html 
     PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
     "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
     
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<title>CAS</title>
		<meta http-equiv="content-type" content="text/html; charset=UTF-8"/>

        <meta name="description" content=" ">
        <meta name="keywords" content=" ">
        <meta name="author" content="605">

        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <base href="http://localhost/cas/">
        <link rel="stylesheet" href="/<?php echo SITE_NAME; ?>/css/styles.css" type="text/css">

        <link href="css/bootstrap.min.css" rel="stylesheet">
        <link rel="stylesheet" href="css/settings.css" media="screen" />
        <link rel="stylesheet" href="css/ddlevelsmenu-base.css">
        <link rel="stylesheet" href="css/ddlevelsmenu-topbar.css">
        <link rel="stylesheet" href="css/prettyPhoto.css">
        <link rel="stylesheet" href="css/slider.css">
        <link href="css/font-awesome.min.css" rel="stylesheet">
        <link href="css/style.css" rel="stylesheet">

        <link rel="shortcut icon" href="#">
		<script src="js/jquery.js"></script>
    </head>
	<body>

    <header>
        <div class="container">
            <div class="row">
                <div class="col-md-3 col-sm-4">
                    <div class="logo">
                        <div class="logo-image">
                            <a href="index.html"><i class="fa fa-photo blue"></i></a>
                        </div>
                        <div class="logo-text">
                            <h1><a href="index.html">CA<span class="lightblue">S</span></a></h1>
                            <div class="logo-meta">SWISS ALPINE CLUB</div>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                </div>

                <div class="col-md-9 col-sm-8">
                    <div class="navi pull-right">
                        <div id="ddtopmenubar" class="mattblackmenu">
                            <ul>

                                <li><a href="login/login" class="bblue"> <i class="fa fa-camera"></i> Login</a></li>
                                <li><a href="sorties/programme" class="bblue"> <i class="fa fa-envelope-o"></i> Programme</a></li>
                                <li><a href="sorties/propositions" class="bblue"> <i class="fa fa-envelope-o"></i> Propositions</a></li>
                                <li><a href="contact" class="bblue"> <i class="fa fa-envelope-o"></i> Contact</a></li>


                            </ul>
                        </div>
                    </div>

                    <div class="navis"></div>

                    <!-- Navbar ends -->

                    <div class="clearfix"></div>

                </div>

            </div>
        </div>
    </header>
